### ISSUE TITLE
Freezing RHN channels fails

### ISSUE THREAD

**Issue by stdevel** [stdevel/satprep#46]
When freezing RHN channels, ``satprep_patch_freeze.py`` fails with the following error:
```
INFO:satprep_patch_freeze:Cloning child-channel 'rhn-tools-rhel-x86_64-server-6' as 'rhn-tools-rhel-x86_64-server-6.sp-sap-2015-11-16'
ERROR:satprep_patch_freeze:Unable to clone base-channel: redstone.xmlrpc.XmlRpcFault: Channels names must not start with 'rhn'
```
The idea is to prepend the prefix instead of appending it.

**Comment by novonilc** [comment]
Can you please fix this issue please.

**Comment by stdevel** [comment]
Fixed in commit 9e478d522f94d39fb002a2f031868735b51fe5ad

**Comment by novonilc** [comment]
Thank you Christian. Your tool is helping us :)

On Fri, 18 Dec 2015 at 05:46 Christian Stankowic <notifications@github.com>
wrote:

> Fixed in commit 9e478d5
> <https://github.com/stdevel/satprep/commit/9e478d522f94d39fb002a2f031868735b51fe5ad>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stdevel/satprep/issues/46#issuecomment-165781742>.
>
-- 
Sent from iPhone

**Comment by stdevel** [comment]
Thank you, I'm glad to hear this! :)

Best wishes,
Christian!

**Comment by novonilc** [comment]
Christian,

I just tried your new build. Opened a blocker issue
satprep_patch_freeze.py not working in new build #50
Can you have a look please

thanks,
Novonil

On Fri, 18 Dec 2015 at 08:48 Christian Stankowic <notifications@github.com>
wrote:

> Thank you, I'm glad to hear this! :)
>
> Best wishes,
> Christian!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stdevel/satprep/issues/46#issuecomment-165833761>.
>
-- 
Sent from iPhone

**Comment by novonilc** [comment]
i am still getting the error with the new build. 


 ./satprep_patch_freeze.py -a auth -g Test_for_satprep
INFO:satprep_patch_freeze:Cloning base-channel 'rhel-x86_64-server-6' as 'sp-2015-12-18.rhel-x86_64-server-6'
INFO:satprep_patch_freeze:Cloning child-channel 'rhn-tools-rhel-x86_64-server-6' as 'sp-2015-12-18.rhn-tools-rhel-x86_64-server-6'
ERROR:satprep_patch_freeze:Unable to clone base-channel: redstone.xmlrpc.XmlRpcFault: unhandled internal exception: The channel parameter rhn-tools-rhel-x86_64-server-6 clone from 2015-12-18 is invalid. It must be at least 6 characters long, begin with a letter, and contain only lowercase letters, digits, '-', ' / ', '_' and '.'.  Also, it cannot begin with 'rhn', 'redhat', or 'red hat'.
INFO:satprep_patch_freeze:Cloning child-channel 'rhel-x86_64-server-extras-6' as 'sp-2015-12-18.rhel-x86_64-server-extras-6'
INFO:satprep_patch_freeze:Cloning child-channel 'rhel-x86_64-server-optional-6' as 'sp-2015-12-18.rhel-x86_64-server-optional-6'
